meta_product_name: "ReMost"
meta_title: "ReMost- Make the most out of remote"
meta_description: "Connect with your colleagues all around the world."
meta_image: "cover.png"
twitter_account: "@ReMost_twitter_account"
